research_task:
  description: >
    Conduct a thorough research about {topic} and {data_needed}
  expected_output: >
    A list with 10 bullet points of matches between {topic} and {data_needed}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    Return true or false if {topic} match with {data_needed}
    Formatted as markdown without '```'
  agent: reporting_analyst
